---
title: "语句和程序结构"
date: 2024-02-29T21:07:48+08:00
---

## 流程控制

### break 语句

break 语句能够结束当前 for、for/in、while、do/while 或者 switch 语句的执行；同时 break 也可以接受一个可选的标签名，来决定跳出的结构语句。语法格式如下：

```js
break label;
```

下面示例设计在客户端查找 document 的 bgColor 属性，如果完全遍历 document 对象，会浪费时间，因此设计一个条件，判断所枚举的属性名是都等于 “bgColor”，如果相等，则使用 break 语句跳出循环。

```js
for (i in document) {
  if (i.toString() == "bgColor") {
    document.write("document." + i + "=" + document[i] + "<br />");
    break;
  }
}
```

在下面嵌套结构中，break 语句并没有跳出 `for/in` 结构，仅仅退出 `switch` 结构。

```js
for (i in document) {
  switch (i.toString()) {
    case "bgColor":
      document.write("document." + i + "=" + document[i] + "<br />");
      break;
    default:
      document.write("没有找到");
  }
}
```

可以为 `for/in` 语句定义一个标签 outloop，然后再最内层的 break 语句中设置该标签名，这样当条件满足时就可以跳出最外层的 `for/in` 循环结构。

```js
outloop: for (i in document) {
  switch (i.toString()) {
    case "bgColor":
      document.write("document." + i + "=" + document[i] + "<br />");
      break outloop;
    default:
      document.write("没有找到");
  }
}
```

### continue 语句

continue 语句用在循环结构内，用于跳过本次循环中剩余的代码，并在表达式的值为真时，继续执行下一次循环。它可以接受一个可选的标签名，来决定跳出的循环语句，

```js
continue label;
```

下面示例使用 continue 语句过滤数组中的字符串值

```js
var a = [1, "hi", 2, "good", "4", , "", 3, 4],
  b = [],
  j = 0;

for (var i in a) {
  if (typeof a[i] == "string") {
    // 如果为字符串，则返回继续下一次循环
    continue;
  }
  b[j++] = a[i]; // 把数字寄存在数组 b
}

document.write(b);
```

> continue 语句只能用在 while、do/while、for、for/in 语句中，对于不同的循环结构，其执行顺序略有不同。

## 异常处理

ECMA-262 规范了 7 中错误类型，具体说明如下，其中 Error 是基类，其他 6 种错误类型是子类，都继承 Error 基类。

- Error: 普通异常，与 throw 语句和 `try/catch` 语句一起使用，属性 name 可以读写异常类型，message 属性可以读写详细错误信息。

- EvalError: 不正确地使用 eval() 方法时抛出。

- SyntaxError: 出现语法错误时抛出。

- RangeError: 数字超出合法范围时抛出。

- ReferenceError: 读取不存在的变量时抛出。

- TypeError: 值的类型发生错误时抛出。

- URIError: URI 编码和解码错误时抛出。

### try/catch/finally 语句

```js
try {
  //..
} catch (e) {
  // 捕获异常，并进行异常处理的代码块
} finally {
  // 后期清理代码块
}
```

在正常情况下，Js 按顺序执行 try 子句中的代码，如果没有发生异常，将会忽略 catch 子句，跳转到 finally 子句中继续执行。

如果 try 子句运行时发生错误，或者使用 throw 语句主动抛出异常，则执行 catch 子句中的代码，同时传入一个参数，引用 Error 对象。

> 不管 try 语句是否完全执行，finally 语句最后都必须要执行，即使使用了跳转语句跳出了异常处理结构，也必须在跳出之前先执行 finally 子句。

下面示例在函数体内设计一个异常处理结构，为每个子句添加一个 return 语句，调用函数后，实际返回是 “finally”，而不是 “try”，因为 finally 子句必须最后执行，把 finally 子句去掉，函数才会返回 “try”。

```js
function test() {
  try {
    return "try";
  } catch (error) {
    return "catch";
  } finally {
    return "finally";
  }
}
console.log(test()); // "finally
```

`try/catch/finally` 语句允许嵌套使用，嵌套的层数不限，同时形成一条词法作用域链。Js 会停止程序的正常执行，并跳转到层级最近的 catch 子句（异常处理器），如果没有找到异常处理器，则会沿着作用域链，检查上一级的 catch 子句，以此类推，直到找到一个异常处理器。如果没有在程序中没有找到任何异常处理器，将会显示错误。

下面代码就是一个多层嵌套的异常结构，在处理一系列的异常时，内层的 catch 子句通过将异常抛出，就可以将异常抛给外层 catch 子句来处理。

```js
try {
  try {
    test();
  } catch (error) {
    if (error.name === "ReferenceError") console.log("错误参考");
    else throw error;
  }
} catch (error) {
  console.log("内层 try/catch 不能处理这个错误");
}
```

### throw 语句

throw 语句能够主动抛出一个异常，语法格式如下：

```sh
throw expression
```

expression 是任意类型的表达式，一般为 Error 对象，或者 Error 子类实例。

当执行 throw 语句时，程序会立即停止执行，只有当使用 `try/catch` 语句捕获到被抛出的值时，程序才会继续执行。

```js
try {
  for (var i = 0; i < 10; i++) {
    if (i > 5) {
      throw new Error("循环变量的值大于 5 了");
    }
    console.log(i);
  }
} catch (error) {}
```

